@echo off
echo ...Assembling...
c:\masm32\bin\ml.exe /c /coff /Cp main.asm
echo ...Linking...
c:\masm32\bin\link.exe /SUBSYSTEM:WINDOWS /LIBPATH:c:\masm32\lib main.obj /OUT:dist\main.exe
echo ...Cleaning...
del *.obj
